### ISSUE TITLE
Problem building iOS app with google analytics

### ISSUE THREAD

**Issue by 11Sheep** [googleanalytics/google-analytics-plugin-for-unity#105]
Hi All,

I am trying to build my code with unity cloud build for iOS using google analytics V4 (the newest) .
My unity version is 5.3.2.

Looking at the log, i get these errors:

4728: [xcode] "_sqlite3_errmsg", referenced from:
4729: [xcode] -[GAISqlStore errorMessage] in libGoogleAnalyticsServices.a(GAISqlStore.o)

4799: [xcode] "_NSSQLiteErrorDomain", referenced from:
4800: [xcode] -[GAIDataStore performBlockAndWait:withError:] in libGoogleAnalyticsServices.a(GAIDataStore.o)
4801: [xcode] "_sqlite3_reset", referenced from:
4802: [xcode] -[GAIAnalyticsPropertiesStore upsertPropertyRecord:] in libGoogleAnalyticsServices.a(GAIAnalyticsPropertiesStore.o)
4803: [xcode] -[GAIAnalyticsPropertiesStore clearPropertiesTable] in libGoogleAnalyticsServices.a(GAIAnalyticsPropertiesStore.o)
4804: [xcode] -[GAIAnalyticsPropertiesStore propertyRecordForTrackingId:] in libGoogleAnalyticsServices.a(GAIAnalyticsPropertiesStore.o)
4805: [xcode] -[GAIAnalyticsPropertiesStore selectStmtWithTrackingId:] in libGoogleAnalyticsServices.a(GAIAnalyticsPropertiesStore.o)
4806: [xcode] -[GAISqlStore rowCountForTableWithName:] in libGoogleAnalyticsServices.a(GAISqlStore.o)
4807: [xcode] -[GAISqlStore tableExists:] in libGoogleAnalyticsServices.a(GAISqlStore.o)
4808: [xcode] -[GAISqlStore dropTableWithName:] in libGoogleAnalyticsServices.a(GAISqlStore.o)
4809: [xcode] ...
4810: [xcode] "_OBJC_CLASS_$_NSManagedObjectContext", referenced from:
4811: [xcode] objc-class-ref in libGoogleAnalyticsServices.a(GAIDataStore.o)
4812: [xcode] "_sqlite3_column_int64", referenced from:
4813: [xcode] -[GAIAnalyticsPropertiesStore propertyRecordForTrackingId:] in libGoogleAnalyticsServices.a(GAIAnalyticsPropertiesStore.o)
4814: [xcode] "_sqlite3_bind_int64", referenced from:
4815: [xcode] -[GAIAnalyticsPropertiesStore bindRecord:toUpsertStatement:] in libGoogleAnalyticsServices.a(GAIAnalyticsPropertiesStore.o)
4816: [xcode] ld: symbol(s) not found for architecture armv7
4817: [xcode] clang: error: linker command failed with exit code 1 (use -v to see invocation)

Any help will be appreciated!

**Comment by swaps-mayekar** [comment]
Did you add following libraries in your Xcode project manually as mentioned [here](https://developers.google.com/analytics/devguides/collection/unity/v4/devguide#ios) ? :

    AdSupport.framework
    CoreData.framework
    SystemConfiguration.framework
    libz.dylib
    libsqlite3.dylib

**Comment by 11Sheep** [comment]
i did and now it is working. But i had lots of other issues on the way....

**Comment by AGTDigital** [comment]
Hi

I'm having the same type of issue.
My configuration :
- Unity 2020.1.3
- XCode 11.7
- Google Analytics SDK V3 with bitcode (Also tried V4, and I can't use GA SDK without bitcode because XCode return error)

I link all libraries and framework as it is asked in Google Analytics SDK but no way..
I tried to use TBD files instead of DYLIB files, but same result...
Can you see any things I should do or an error ?

I use : proj.GetUnityMainTargetGuid();

You can see on screenshot the different errors and the libraries configuration
The library libsqlite seams to be not linked but I don't understand why..


<img width="706" alt="Capture d’écran 2020-09-03 à 12 10 13" src="https://user-images.githubusercontent.com/70696359/92103505-5acc0a00-ede0-11ea-96bb-782d3da52f27.png">
<img width="706" alt="Capture d’écran 2020-09-03 à 12 09 47" src="https://user-images.githubusercontent.com/70696359/92103511-5b64a080-ede0-11ea-8233-f4879f4830f5.png">
<img width="1130" alt="Capture d’écran 2020-09-03 à 12 08 54" src="https://user-images.githubusercontent.com/70696359/92103513-5b64a080-ede0-11ea-9eb4-c53455674a3c.png">
