### ISSUE TITLE
Android READ_PHONE_STATE permission

### ISSUE THREAD

**Issue by YY1377** [googleanalytics/google-analytics-plugin-for-unity#15]
First, thank you for this great plugin!
The problem is after exporting the project for Android in Unity, I see an extra permission in manifest.xml.
Without plugin, it doesn't appear. Is it an expected result? Many users do not want to download the application when they see read_phone_state permission.

**Comment by turkenh** [comment]
Can you reopen this issue:
This issue is still valid, there is still a call to SystemInfo.deviceUniqueIdentifier which results this permission. Which is shown scary on Android 6.0 like "Allow <app> to make and manage phone calls"

https://github.com/googleanalytics/google-analytics-plugin-for-unity/blob/master/source/Plugins/GoogleAnalyticsV3/GoogleAnalyticsMPV3.cs#L62
